
DELETE http://localhost:3001/api/blogs/5cb47751ea455e0928249ef7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhc2kiLCJpZCI6IjVjYjRjYzM2YzM0YTE2MjczMGViZmQxOSIsImlhdCI6MTU1NTM1MjY0OH0.By-2b3EoBTzR1CCIBGm4l0a2XXW606Il9rKrE-ln0vY